server {
    listen 80;
    server_name localhost;

    # Redirige la raíz limpia (http://192.168.3.35/) a /portal-rh/
    location = / {
        return 301 /portal-rh/;
    }

    # Sirve los archivos de React bajo la subruta /portal-rh/
    location /portal-rh/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /portal-rh/index.html;
    }
}